### PR TITLE
Added compilation in library mode

### PR DESCRIPTION
**Pull request by cybervaca**
Added compilation in library mode

### CODE REVIEW

**Review by phra — CHANGES_REQUESTED** [review]
i think the template of the DLL is missing (DllMain)

**Comment by cybervaca** [comment]
> i think the template of the DLL is missing (DllMain)

Not, every thing is ok. Check

**Comment by cybervaca** [comment]
imagen

**Comment by cybervaca** [comment]
I have now consented to go through the binary "go" fish, hehe

**Comment by phra** [comment]
> > i think the template of the DLL is missing (DllMain)
> 
> Not, every thing is ok. Check
> 
> Rundll32 pezor.dll,main

try with `LoadLibraryA("pezor.dll")`, the payload won't execute since `DllMain` is missing.

**Comment by cybervaca** [comment]
I can show you if you want. I can share your screen if you want and you see it. I charge it with rundll32.exe pezor.dll,main

**Comment by phra** [comment]
superseded by https://github.com/phra/PEzor/pull/9

**Pull request closed without merging**
